export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const GET_COMMENTS_BY_FOLDER_ID = 'GET_COMMENTS_BY_FOLDER_ID';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
