export const GET_DOSSIER = 'GET_DOSSIER';
export const NEW_FOLDER = 'NEW_FOLDER';
export const FOLDER_BY_ID = 'FOLDER_BY_ID';
export const CONFIRM_FOLDER = 'CONFIRM_FOLDER';
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS';
export const GET_DRAFT_FOLDER = 'GET_DRAFT_FOLDER';
export const SET_ACTIVE_FOLDER = 'SET_ACTIVE_FOLDER';
export const DELETE_ACTIVE_FOLDER = 'DELETE_ACTIVE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const UPDATE_FOLDER = 'UPDATE_FOLDER';
export const REMOVE_CANDIDATE_FROM_FOLDER = 'REMOVE_CANDIDATE_FROM_FOLDER';
export const ADD_CANDIDATE_TO_ACTIVE_FOLDER = 'ADD_CANDIDATE_TO_ACTIVE_FOLDER';
export const REMOVE_CANDIDATE_FROM_ACTIVE_FOLDER =
  'REMOVE_CANDIDATE_FROM_ACTIVE_FOLDER';
